### ISSUE TITLE
Mac 上n播放下一首报错退出了

### ISSUE THREAD

**Issue by damoncoo** [izhengzhixian/nineku.fm#1]
Mac 上Iterm2 n播放下一首报错退出了

![1607915498662](https://user-images.githubusercontent.com/4880373/102036219-37f8bb00-3dfd-11eb-9cb0-0c6cabd7ab82.jpg)

**Comment by izhengzhixian** [comment]
你可以用 `npm install -g nineku.fm --mpg123-backend=openal` 试试
